In [ ]:
import pandas as pd


data = [[1, 'Wang', 'Allen'], [2, 'Alice', 'Bob']]

person = pd.DataFrame(data, columns=['personId', 'firstName', 'lastName']).astype(
    {'personId': 'Int64', 'firstName': 'object', 'lastName': 'object'})

data = [[1, 2, 'New York City', 'New York'], [2, 3, 'Leetcode', 'California']]

address = pd.DataFrame(data, columns=['addressId', 'personId', 'city', 'state']).astype(
    {'addressId': 'Int64', 'personId': 'Int64', 'city': 'object', 'state': 'object'})

In [ ]:
import pandas as pd

# initialize data of lists.
data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}

# Create DataFrame
df = pd.DataFrame(data)

df.index

In [ ]:
import pandas as pd

data = {'Name': ['Jake', 'Mike'],
        'Age': [25, 30],
        'Salary': [50000, 55000]}
df = pd.DataFrame(data)
df_index = df.set_index('Name')
df_index.iloc[0],df_index.loc['Jake']
df_index

In [1]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
# Display the entire DataFrame
print(df)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [2]:
df.loc[0:2, ['Name','Age']]
df[['Age','Name','Gender']]
df.iat[1,3]

np.int64(55000)

In [ ]:
df

In [ ]:
df.loc[0][['Name','Age']]
df.iloc[[1,2],[0,1,2]]

In [6]:
df.query("Age > 25")

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [9]:
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)

df1

     Name  Age    Address Qualification  Salary
0  Gaurav   22  Allahabad           MCA    1000
1    Anuj   32    Kannuaj           Phd    2000
2  Dhiraj   12  Allahabad          Bcom    3000
3  Hitesh   52    Kannuaj        B.hons    4000

In [10]:
data = [[1, 'Wang', 'Allen'], [2, 'Alice', 'Bob']]
person = pd.DataFrame(data, columns=['personId', 'firstName', 'lastName']).astype(
    {'personId': 'Int64', 'firstName': 'object', 'lastName': 'object'})
data = [[1, 2, 'New York City', 'New York'], [2, 3, 'Leetcode', 'California']]
address = pd.DataFrame(data, columns=['addressId', 'personId', 'city', 'state']).astype(
    {'addressId': 'Int64', 'personId': 'Int64', 'city': 'object', 'state': 'object'})

person

   personId firstName lastName
0         1      Wang    Allen
1         2     Alice      Bob

In [17]:
df = person.merge(address, how='left',on=['personId'])[['firstName','lastName','city','state']]
df

  firstName lastName           city     state
0      Wang    Allen            NaN       NaN
1     Alice      Bob  New York City  New York

# LEETCODE

In [ ]:
# 177. Nth Highest Salary

data = [[1, 100], [2, 200], [3, 300]]
employee = pd.DataFrame(data, columns=['Id', 'Salary']).astype({'Id':'Int64', 'Salary':'Int64'})